version: '3.1'

services:
  db:
    container_name: db
    image: mysql
    volumes:
      - mydb:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=BUDGET
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3306:3306"

  app:
    container_name: app
    image: budget-image
    ports:
      - "5000:5000"
    build: app


volumes:
  mydb: