CREATE DATABASE IF NOT EXISTS BUDGET;
USE BUDGET;

CREATE TABLE IF NOT EXISTS USER (
	IDX INT NOT NULL, 
	USERNAME text, 
    PRIMARY KEY (IDX));

CREATE TABLE IF NOT EXISTS PROJECT (
	IDX INT NOT NULL, 
	DATE date, 
	NAME text, 
	CREATOR text,
    PRIMARY KEY (IDX));
    
CREATE TABLE IF NOT EXISTS PROJECT_DATA (
    IDX INT NOT NULL,
    DATE DATE,
    PROJECT_NAME TEXT,
    CLASS TEXT,
    TYPE TEXT,
    NAME TEXT,
    VALUE REAL,
    SENDER TEXT,
    RECIPIENT TEXT,
    CREATOR TEXT,
    PRIMARY KEY (IDX)
);

CREATE TABLE IF NOT EXISTS TRANSACTION_TYPES (
	IDX INT NOT NULL,
	TYPE text,
    PRIMARY KEY (IDX));

CREATE TABLE IF NOT EXISTS TRANSACTION_CLASSES(
	IDX INT NOT NULL,
	CLASS text,
    PRIMARY KEY (IDX));

CREATE TABLE IF NOT EXISTS TRANSACTION_SENDER (
	IDX INT NOT NULL,
	SENDER text,
    PRIMARY KEY (IDX));

CREATE TABLE IF NOT EXISTS TRANSACTION_RECIPIENT (
	IDX INT NOT NULL,
	RECIPIENT text,
    PRIMARY KEY (IDX));
